workshop:
  gitops:
    source:
      repoUrl: https://github.com/streams-kafka-workshop/helm.git
      targetRevision: main
  amqstreams:
    source:
      repoUrl: https://github.com/streams-kafka-workshop/helm.git
      targetRevision: main
  keycloak:
    source:
      repoUrl: https://github.com/btison/streams-kafka-workshop-helm.git
      targetRevision: keycloak
  argocd:
    namespace:
      syncwave: "-1"
    gitops:
      syncwave: "-1" 
    amqstreams:
      syncwave: "0"
    keycloak:
      syncwave: "-1"

devspaces:
  devspaces:
    source:
      repoUrl: https://github.com/streams-kafka-workshop/helm.git
      targetRevision: main
  argocd:
    devspaces:
      syncwave: "-1"

amq-streams-operator:
  argocd:
    operator:
      syncwave: "-2"
amq-streams-console-operator:
  argocd:
    operator:
      syncwave: "-2"
devspaces-operator:
  argocd:
    operator:
      syncwave: "-2"
