{{- range untilStep 0 (.Values.loop.count | int64 | int) 1 }}
{{ $loop := printf "%s%s" $.Values.loop.prefix ((add . 1) | toString) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.applicationName }}-{{ $loop }}
  namespace: {{ $.Values.applicationNamespace }}
  annotations:
    {{- include "amq-streams-application.argocd-syncwave" $ | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    name: ""
    namespace: {{ $.Values.destinationNamespace }}-{{ $loop }}
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  source:
    repoURL: {{ $.Values.source.repoUrl }}
    targetRevision: {{ $.Values.source.targetRevision }}
    path: {{ $.Values.source.path }}
    helm:
      valuesObject:
{{- end }}