nameOverride: "amq-streams"
fullnameOverride: ""

namespace: openshift-operators

subscription:
  channel: amq-streams-3.0.x
  installPlanApproval: Automatic
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    resources:
      requests:
        memory: 384Mi
      limits:
        memory: 1Gi

argocd:
  enabled: true
  operator:
    syncwave: "-2"
